### ISSUE TITLE
[BUG]Краш при использовании ИЦ2 инструментов.

### ISSUE THREAD

**Issue by Pilad** [IdealIndustrial/GT5Unofficial#231]
**Описание**
Краш при использовании ИЦ2 инструментов. 

**Воспроизведение**
Левый клик инструментом и вылет.

**Дополнительная информация**
[Скриншоты/Логи/Краши/Видеоролики относящиеся к багу](https://paste.ee/p/Mo6lP#s=0&l=5429)

**Среда**
ИИС 1.18.0 , одиночная игра.

**Comment by Pilad** [comment]
[22:01:33] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking memory connection
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186) ~[bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2147483647
	at idealindustrial.hooks.II_EUtoRFPatch$DummyEUtoRFCompatManager.discharge(II_EUtoRFPatch.java:90) ~[II_EUtoRFPatch$DummyEUtoRFCompatManager.class:?]
	at ic2.core.item.GatewayElectricItemManager.discharge(GatewayElectricItemManager.java:26) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.ElectricItemManager.chargeFromArmor(ElectricItemManager.java:151) ~[ElectricItemManager.class:?]
	at ic2.core.item.GatewayElectricItemManager.chargeFromArmor(GatewayElectricItemManager.java:60) ~[GatewayElectricItemManager.class:?]
	at ic2.core.item.ElectricItemManager.use(ElectricItemManager.java:120) ~[ElectricItemManager.class:?]
	at ic2.core.item.GatewayElectricItemManager.use(GatewayElectricItemManager.java:50) ~[GatewayElectricItemManager.class:?]
	at gravisuite.ItemAdvChainsaw.func_77644_a(ItemAdvChainsaw.java:139) ~[ItemAdvChainsaw.class:?]
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:299) ~[add.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1282) ~[yz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821) ~[nh.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
	... 5 more
[22:01:34] [Server thread/ERROR]: This crash report has been saved to: C:\Users\usman\Downloads\MultiMC\instances\1.7.10\.minecraft\crash-reports\crash-2022-07-08_22.01.33-server.txt
[22:01:34] [Server thread/INFO]: Stopping server
[22:01:34] [Server thread/INFO]: Saving players
[22:01:34] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/8/22 10:01 PM
Description: Ticking memory connection

java.lang.ArrayIndexOutOfBoundsException: 2147483647
	at idealindustrial.hooks.II_EUtoRFPatch$DummyEUtoRFCompatManager.discharge(II_EUtoRFPatch.java:90)
	at ic2.core.item.GatewayElectricItemManager.discharge(GatewayElectricItemManager.java:26)
	at ic2.core.item.ElectricItemManager.chargeFromArmor(ElectricItemManager.java:151)
	at ic2.core.item.GatewayElectricItemManager.chargeFromArmor(GatewayElectricItemManager.java:60)
	at ic2.core.item.ElectricItemManager.use(ElectricItemManager.java:120)
	at ic2.core.item.GatewayElectricItemManager.use(GatewayElectricItemManager.java:50)
	at gravisuite.ItemAdvChainsaw.func_77644_a(ItemAdvChainsaw.java:139)
	at net.minecraft.item.ItemStack.func_77961_a(ItemStack.java:299)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1282)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Pilad** [comment]
Попробовал, вроде не вызывается краш.Автор с вк
![изображение](https://user-images.githubusercontent.com/9840821/178100857-6bb56390-e774-408f-b762-d497e23a4a6b.png)

**Comment by Pilad** [comment]
Так же проблема с хуком https://vk.com/wall-66455432_36428
Логи: https://disk.yandex.ru/d/A7cc6HRfb9oxyg

**Comment by WiseProjects** [comment]
не воспроизводится
